default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: short_url_dev
  username: postgres
  password: password
  # host: db

production:
  database: railway
  username: postgres
  password: 6936
  host: containers-us-west-45.railway.app
